### ISSUE TITLE
Loop Examples

### ISSUE THREAD

**Issue by kmgovind** [raypatriots71/Operation_Gamma#4]
requests: sample code for loops
({[0 to 5]}         .                                               dot
then?
how do we write the body of the loops? otherwise, looks good. we can work on switch and stuff if you'd like

**Comment by kmgovind** [comment]
Example of Bubble sort in our language:
length.(6)	
{ a.[0 to length] }(
	{ b.[(length+1) to length] }(
		{ array[a] < array[b] }(
			temp.array[b]
			array[a].array[b]
			array[b].temp
)))

**Comment by smirki** [comment]
[ ### to @@@ ] - with the to looks for one variable ( ### ) increasing or decreasing in value to another set value @@@.
