### ISSUE TITLE
Simple errors and clarification requests

### ISSUE THREAD

**Issue by kmgovind** [raypatriots71/Operation_Gamma#5]
Scope.#packageC.extend                      //is packageC a thing or do we make it?
side, segmentHeight, hexagonArea, costTheta.(0.866025)          //again, fix var declaration

**Comment by smirki** [comment]
Depending on the platform the code is being built for, Scope will have its own set of rules (Ie. built for the web with the scope of the DOM etc.)
packageC would be an example of a cross-language library using HAXM or something of the sort. 
Var Declaration is now fixed.
